// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4096' | (string & {});
};

export type RegisterData = {
    body?: {
        password: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterResponses = {
    /**
     * User created successfully
     */
    201: {
        message: string;
        success: boolean;
        user?: {
            hasDownloadedResticPassword: boolean;
            id: number;
            username: string;
        };
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body?: {
        password: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginResponses = {
    /**
     * Login successful
     */
    200: {
        message: string;
        success: boolean;
        user?: {
            hasDownloadedResticPassword: boolean;
            id: number;
            username: string;
        };
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: boolean;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeResponses = {
    /**
     * Current user information
     */
    200: {
        message: string;
        success: boolean;
        user?: {
            hasDownloadedResticPassword: boolean;
            id: number;
            username: string;
        };
    };
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type GetStatusResponses = {
    /**
     * Authentication system status
     */
    200: {
        hasUsers: boolean;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type ChangePasswordData = {
    body?: {
        currentPassword: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type ChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        message: string;
        success: boolean;
    };
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type ListVolumesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/volumes';
};

export type ListVolumesResponses = {
    /**
     * A list of volumes
     */
    200: Array<{
        autoRemount: boolean;
        config: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
        createdAt: number;
        id: number;
        lastError: string | null;
        lastHealthCheck: number;
        name: string;
        shortId: string;
        status: 'error' | 'mounted' | 'unmounted';
        type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
        updatedAt: number;
    }>;
};

export type ListVolumesResponse = ListVolumesResponses[keyof ListVolumesResponses];

export type CreateVolumeData = {
    body?: {
        config: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/volumes';
};

export type CreateVolumeResponses = {
    /**
     * Volume created successfully
     */
    201: {
        autoRemount: boolean;
        config: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
        createdAt: number;
        id: number;
        lastError: string | null;
        lastHealthCheck: number;
        name: string;
        shortId: string;
        status: 'error' | 'mounted' | 'unmounted';
        type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
        updatedAt: number;
    };
};

export type CreateVolumeResponse = CreateVolumeResponses[keyof CreateVolumeResponses];

export type TestConnectionData = {
    body?: {
        config: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/api/v1/volumes/test-connection';
};

export type TestConnectionResponses = {
    /**
     * Connection test result
     */
    200: {
        message: string;
        success: boolean;
    };
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type DeleteVolumeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}';
};

export type DeleteVolumeResponses = {
    /**
     * Volume deleted successfully
     */
    200: {
        message: string;
    };
};

export type DeleteVolumeResponse = DeleteVolumeResponses[keyof DeleteVolumeResponses];

export type GetVolumeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}';
};

export type GetVolumeErrors = {
    /**
     * Volume not found
     */
    404: unknown;
};

export type GetVolumeResponses = {
    /**
     * Volume details
     */
    200: {
        statfs: {
            free: number;
            total: number;
            used: number;
        };
        volume: {
            autoRemount: boolean;
            config: {
                backend: 'directory';
                path: string;
                readOnly?: false;
            } | {
                backend: 'nfs';
                exportPath: string;
                server: string;
                version: '3' | '4' | '4.1';
                port?: number;
                readOnly?: boolean;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                readOnly?: boolean;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                username: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                knownHosts?: string;
                password?: string;
                privateKey?: string;
                readOnly?: boolean;
            } | {
                backend: 'smb';
                password: string;
                server: string;
                share: string;
                username: string;
                vers?: '1.0' | '2.0' | '2.1' | '3.0';
                port?: number;
                domain?: string;
                readOnly?: boolean;
            } | {
                backend: 'webdav';
                path: string;
                server: string;
                port?: number;
                password?: string;
                readOnly?: boolean;
                ssl?: boolean;
                username?: string;
            };
            createdAt: number;
            id: number;
            lastError: string | null;
            lastHealthCheck: number;
            name: string;
            shortId: string;
            status: 'error' | 'mounted' | 'unmounted';
            type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
            updatedAt: number;
        };
    };
};

export type GetVolumeResponse = GetVolumeResponses[keyof GetVolumeResponses];

export type UpdateVolumeData = {
    body?: {
        autoRemount?: boolean;
        config?: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
        name?: string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}';
};

export type UpdateVolumeErrors = {
    /**
     * Volume not found
     */
    404: unknown;
};

export type UpdateVolumeResponses = {
    /**
     * Volume updated successfully
     */
    200: {
        autoRemount: boolean;
        config: {
            backend: 'directory';
            path: string;
            readOnly?: false;
        } | {
            backend: 'nfs';
            exportPath: string;
            server: string;
            version: '3' | '4' | '4.1';
            port?: number;
            readOnly?: boolean;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            readOnly?: boolean;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            username: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            knownHosts?: string;
            password?: string;
            privateKey?: string;
            readOnly?: boolean;
        } | {
            backend: 'smb';
            password: string;
            server: string;
            share: string;
            username: string;
            vers?: '1.0' | '2.0' | '2.1' | '3.0';
            port?: number;
            domain?: string;
            readOnly?: boolean;
        } | {
            backend: 'webdav';
            path: string;
            server: string;
            port?: number;
            password?: string;
            readOnly?: boolean;
            ssl?: boolean;
            username?: string;
        };
        createdAt: number;
        id: number;
        lastError: string | null;
        lastHealthCheck: number;
        name: string;
        shortId: string;
        status: 'error' | 'mounted' | 'unmounted';
        type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
        updatedAt: number;
    };
};

export type UpdateVolumeResponse = UpdateVolumeResponses[keyof UpdateVolumeResponses];

export type MountVolumeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}/mount';
};

export type MountVolumeResponses = {
    /**
     * Volume mounted successfully
     */
    200: {
        status: 'error' | 'mounted' | 'unmounted';
        error?: string;
    };
};

export type MountVolumeResponse = MountVolumeResponses[keyof MountVolumeResponses];

export type UnmountVolumeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}/unmount';
};

export type UnmountVolumeResponses = {
    /**
     * Volume unmounted successfully
     */
    200: {
        status: 'error' | 'mounted' | 'unmounted';
        error?: string;
    };
};

export type UnmountVolumeResponse = UnmountVolumeResponses[keyof UnmountVolumeResponses];

export type HealthCheckVolumeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/volumes/{name}/health-check';
};

export type HealthCheckVolumeErrors = {
    /**
     * Volume not found
     */
    404: unknown;
};

export type HealthCheckVolumeResponses = {
    /**
     * Volume health check result
     */
    200: {
        status: 'error' | 'mounted' | 'unmounted';
        error?: string;
    };
};

export type HealthCheckVolumeResponse = HealthCheckVolumeResponses[keyof HealthCheckVolumeResponses];

export type ListFilesData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Subdirectory path to list (relative to volume root)
         */
        path?: string;
    };
    url: '/api/v1/volumes/{name}/files';
};

export type ListFilesResponses = {
    /**
     * List of files in the volume
     */
    200: {
        files: Array<{
            name: string;
            path: string;
            type: 'directory' | 'file';
            modifiedAt?: number;
            size?: number;
        }>;
        path: string;
    };
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type BrowseFilesystemData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Directory path to browse (absolute path, defaults to /)
         */
        path?: string;
    };
    url: '/api/v1/volumes/filesystem/browse';
};

export type BrowseFilesystemResponses = {
    /**
     * List of directories in the specified path
     */
    200: {
        directories: Array<{
            name: string;
            path: string;
            type: 'directory' | 'file';
            modifiedAt?: number;
            size?: number;
        }>;
        path: string;
    };
};

export type BrowseFilesystemResponse = BrowseFilesystemResponses[keyof BrowseFilesystemResponses];

export type ListRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repositories';
};

export type ListRepositoriesResponses = {
    /**
     * List of repositories
     */
    200: Array<{
        compressionMode: 'auto' | 'max' | 'off' | null;
        config: {
            accessKeyId: string;
            backend: 'r2';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accessKeyId: string;
            backend: 's3';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accountKey: string;
            accountName: string;
            backend: 'azure';
            container: string;
            customPassword?: string;
            endpointSuffix?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'gcs';
            bucket: string;
            credentialsJson: string;
            projectId: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'local';
            name: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            path?: string;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'rest';
            url: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            password?: string;
            path?: string;
            username?: string;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            privateKey: string;
            user: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            customPassword?: string;
            isExistingRepository?: boolean;
            knownHosts?: string;
        };
        createdAt: number;
        id: string;
        lastChecked: number | null;
        lastError: string | null;
        name: string;
        shortId: string;
        status: 'error' | 'healthy' | 'unknown' | null;
        type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
        updatedAt: number;
    }>;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type CreateRepositoryData = {
    body?: {
        config: {
            accessKeyId: string;
            backend: 'r2';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accessKeyId: string;
            backend: 's3';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accountKey: string;
            accountName: string;
            backend: 'azure';
            container: string;
            customPassword?: string;
            endpointSuffix?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'gcs';
            bucket: string;
            credentialsJson: string;
            projectId: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'local';
            name: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            path?: string;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'rest';
            url: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            password?: string;
            path?: string;
            username?: string;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            privateKey: string;
            user: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            customPassword?: string;
            isExistingRepository?: boolean;
            knownHosts?: string;
        };
        name: string;
        compressionMode?: 'auto' | 'max' | 'off';
    };
    path?: never;
    query?: never;
    url: '/api/v1/repositories';
};

export type CreateRepositoryResponses = {
    /**
     * Repository created successfully
     */
    201: {
        message: string;
        repository: {
            id: string;
            name: string;
            shortId: string;
        };
    };
};

export type CreateRepositoryResponse = CreateRepositoryResponses[keyof CreateRepositoryResponses];

export type ListRcloneRemotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/rclone-remotes';
};

export type ListRcloneRemotesResponses = {
    /**
     * List of rclone remotes
     */
    200: Array<{
        name: string;
        type: string;
    }>;
};

export type ListRcloneRemotesResponse = ListRcloneRemotesResponses[keyof ListRcloneRemotesResponses];

export type DeleteRepositoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}';
};

export type DeleteRepositoryResponses = {
    /**
     * Repository deleted successfully
     */
    200: {
        message: string;
    };
};

export type DeleteRepositoryResponse = DeleteRepositoryResponses[keyof DeleteRepositoryResponses];

export type GetRepositoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}';
};

export type GetRepositoryResponses = {
    /**
     * Repository details
     */
    200: {
        compressionMode: 'auto' | 'max' | 'off' | null;
        config: {
            accessKeyId: string;
            backend: 'r2';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accessKeyId: string;
            backend: 's3';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accountKey: string;
            accountName: string;
            backend: 'azure';
            container: string;
            customPassword?: string;
            endpointSuffix?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'gcs';
            bucket: string;
            credentialsJson: string;
            projectId: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'local';
            name: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            path?: string;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'rest';
            url: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            password?: string;
            path?: string;
            username?: string;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            privateKey: string;
            user: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            customPassword?: string;
            isExistingRepository?: boolean;
            knownHosts?: string;
        };
        createdAt: number;
        id: string;
        lastChecked: number | null;
        lastError: string | null;
        name: string;
        shortId: string;
        status: 'error' | 'healthy' | 'unknown' | null;
        type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
        updatedAt: number;
    };
};

export type GetRepositoryResponse = GetRepositoryResponses[keyof GetRepositoryResponses];

export type UpdateRepositoryData = {
    body?: {
        compressionMode?: 'auto' | 'max' | 'off';
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}';
};

export type UpdateRepositoryErrors = {
    /**
     * Repository not found
     */
    404: unknown;
    /**
     * Repository with this name already exists
     */
    409: unknown;
};

export type UpdateRepositoryResponses = {
    /**
     * Repository updated successfully
     */
    200: {
        compressionMode: 'auto' | 'max' | 'off' | null;
        config: {
            accessKeyId: string;
            backend: 'r2';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accessKeyId: string;
            backend: 's3';
            bucket: string;
            endpoint: string;
            secretAccessKey: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            accountKey: string;
            accountName: string;
            backend: 'azure';
            container: string;
            customPassword?: string;
            endpointSuffix?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'gcs';
            bucket: string;
            credentialsJson: string;
            projectId: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'local';
            name: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            path?: string;
        } | {
            backend: 'rclone';
            path: string;
            remote: string;
            customPassword?: string;
            isExistingRepository?: boolean;
        } | {
            backend: 'rest';
            url: string;
            customPassword?: string;
            isExistingRepository?: boolean;
            password?: string;
            path?: string;
            username?: string;
        } | {
            backend: 'sftp';
            host: string;
            path: string;
            privateKey: string;
            user: string;
            port?: number;
            skipHostKeyCheck?: boolean;
            customPassword?: string;
            isExistingRepository?: boolean;
            knownHosts?: string;
        };
        createdAt: number;
        id: string;
        lastChecked: number | null;
        lastError: string | null;
        name: string;
        shortId: string;
        status: 'error' | 'healthy' | 'unknown' | null;
        type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
        updatedAt: number;
    };
};

export type UpdateRepositoryResponse = UpdateRepositoryResponses[keyof UpdateRepositoryResponses];

export type ListSnapshotsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        backupId?: string;
    };
    url: '/api/v1/repositories/{id}/snapshots';
};

export type ListSnapshotsResponses = {
    /**
     * List of snapshots
     */
    200: Array<{
        duration: number;
        paths: Array<string>;
        short_id: string;
        size: number;
        tags: Array<string>;
        time: number;
    }>;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type DeleteSnapshotData = {
    body?: never;
    path: {
        id: string;
        snapshotId: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/snapshots/{snapshotId}';
};

export type DeleteSnapshotResponses = {
    /**
     * Snapshot deleted successfully
     */
    200: {
        message: string;
    };
};

export type DeleteSnapshotResponse = DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type GetSnapshotDetailsData = {
    body?: never;
    path: {
        id: string;
        snapshotId: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/snapshots/{snapshotId}';
};

export type GetSnapshotDetailsResponses = {
    /**
     * Snapshot details
     */
    200: {
        duration: number;
        paths: Array<string>;
        short_id: string;
        size: number;
        tags: Array<string>;
        time: number;
    };
};

export type GetSnapshotDetailsResponse = GetSnapshotDetailsResponses[keyof GetSnapshotDetailsResponses];

export type ListSnapshotFilesData = {
    body?: never;
    path: {
        id: string;
        snapshotId: string;
    };
    query?: {
        path?: string;
    };
    url: '/api/v1/repositories/{id}/snapshots/{snapshotId}/files';
};

export type ListSnapshotFilesResponses = {
    /**
     * List of files and directories in the snapshot
     */
    200: {
        files: Array<{
            name: string;
            path: string;
            type: string;
            atime?: string;
            ctime?: string;
            gid?: number;
            mode?: number;
            mtime?: string;
            size?: number;
            uid?: number;
        }>;
        snapshot: {
            hostname: string;
            id: string;
            paths: Array<string>;
            short_id: string;
            time: string;
        };
    };
};

export type ListSnapshotFilesResponse = ListSnapshotFilesResponses[keyof ListSnapshotFilesResponses];

export type RestoreSnapshotData = {
    body?: {
        snapshotId: string;
        delete?: boolean;
        exclude?: Array<string>;
        excludeXattr?: Array<string>;
        include?: Array<string>;
        overwrite?: 'always' | 'if-changed' | 'if-newer' | 'never';
        targetPath?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/restore';
};

export type RestoreSnapshotResponses = {
    /**
     * Snapshot restored successfully
     */
    200: {
        filesRestored: number;
        filesSkipped: number;
        message: string;
        success: boolean;
    };
};

export type RestoreSnapshotResponse = RestoreSnapshotResponses[keyof RestoreSnapshotResponses];

export type DoctorRepositoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/doctor';
};

export type DoctorRepositoryResponses = {
    /**
     * Doctor operation completed
     */
    200: {
        steps: Array<{
            error: string | null;
            output: string | null;
            step: string;
            success: boolean;
        }>;
        success: boolean;
    };
};

export type DoctorRepositoryResponse = DoctorRepositoryResponses[keyof DoctorRepositoryResponses];

export type ListBackupSchedulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/backups';
};

export type ListBackupSchedulesResponses = {
    /**
     * List of backup schedules
     */
    200: Array<{
        createdAt: number;
        cronExpression: string;
        enabled: boolean;
        excludeIfPresent: Array<string> | null;
        excludePatterns: Array<string> | null;
        id: number;
        includePatterns: Array<string> | null;
        lastBackupAt: number | null;
        lastBackupError: string | null;
        lastBackupStatus: 'error' | 'in_progress' | 'success' | 'warning' | null;
        name: string;
        nextBackupAt: number | null;
        oneFileSystem: boolean;
        repository: {
            compressionMode: 'auto' | 'max' | 'off' | null;
            config: {
                accessKeyId: string;
                backend: 'r2';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accessKeyId: string;
                backend: 's3';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accountKey: string;
                accountName: string;
                backend: 'azure';
                container: string;
                customPassword?: string;
                endpointSuffix?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'gcs';
                bucket: string;
                credentialsJson: string;
                projectId: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'local';
                name: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                path?: string;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'rest';
                url: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                password?: string;
                path?: string;
                username?: string;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                privateKey: string;
                user: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                customPassword?: string;
                isExistingRepository?: boolean;
                knownHosts?: string;
            };
            createdAt: number;
            id: string;
            lastChecked: number | null;
            lastError: string | null;
            name: string;
            shortId: string;
            status: 'error' | 'healthy' | 'unknown' | null;
            type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
            updatedAt: number;
        };
        repositoryId: string;
        retentionPolicy: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        } | null;
        shortId: string;
        updatedAt: number;
        volume: {
            autoRemount: boolean;
            config: {
                backend: 'directory';
                path: string;
                readOnly?: false;
            } | {
                backend: 'nfs';
                exportPath: string;
                server: string;
                version: '3' | '4' | '4.1';
                port?: number;
                readOnly?: boolean;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                readOnly?: boolean;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                username: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                knownHosts?: string;
                password?: string;
                privateKey?: string;
                readOnly?: boolean;
            } | {
                backend: 'smb';
                password: string;
                server: string;
                share: string;
                username: string;
                vers?: '1.0' | '2.0' | '2.1' | '3.0';
                port?: number;
                domain?: string;
                readOnly?: boolean;
            } | {
                backend: 'webdav';
                path: string;
                server: string;
                port?: number;
                password?: string;
                readOnly?: boolean;
                ssl?: boolean;
                username?: string;
            };
            createdAt: number;
            id: number;
            lastError: string | null;
            lastHealthCheck: number;
            name: string;
            shortId: string;
            status: 'error' | 'mounted' | 'unmounted';
            type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
            updatedAt: number;
        };
        volumeId: number;
    }>;
};

export type ListBackupSchedulesResponse = ListBackupSchedulesResponses[keyof ListBackupSchedulesResponses];

export type CreateBackupScheduleData = {
    body?: {
        cronExpression: string;
        enabled: boolean;
        name: string;
        repositoryId: string;
        volumeId: number;
        excludeIfPresent?: Array<string>;
        excludePatterns?: Array<string>;
        includePatterns?: Array<string>;
        oneFileSystem?: boolean;
        retentionPolicy?: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        };
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/backups';
};

export type CreateBackupScheduleResponses = {
    /**
     * Backup schedule created successfully
     */
    201: {
        createdAt: number;
        cronExpression: string;
        enabled: boolean;
        excludeIfPresent: Array<string> | null;
        excludePatterns: Array<string> | null;
        id: number;
        includePatterns: Array<string> | null;
        lastBackupAt: number | null;
        lastBackupError: string | null;
        lastBackupStatus: 'error' | 'in_progress' | 'success' | 'warning' | null;
        name: string;
        nextBackupAt: number | null;
        oneFileSystem: boolean;
        repositoryId: string;
        retentionPolicy: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        } | null;
        shortId: string;
        updatedAt: number;
        volumeId: number;
    };
};

export type CreateBackupScheduleResponse = CreateBackupScheduleResponses[keyof CreateBackupScheduleResponses];

export type DeleteBackupScheduleData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}';
};

export type DeleteBackupScheduleResponses = {
    /**
     * Backup schedule deleted successfully
     */
    200: {
        success: boolean;
    };
};

export type DeleteBackupScheduleResponse = DeleteBackupScheduleResponses[keyof DeleteBackupScheduleResponses];

export type GetBackupScheduleData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}';
};

export type GetBackupScheduleResponses = {
    /**
     * Backup schedule details
     */
    200: {
        createdAt: number;
        cronExpression: string;
        enabled: boolean;
        excludeIfPresent: Array<string> | null;
        excludePatterns: Array<string> | null;
        id: number;
        includePatterns: Array<string> | null;
        lastBackupAt: number | null;
        lastBackupError: string | null;
        lastBackupStatus: 'error' | 'in_progress' | 'success' | 'warning' | null;
        name: string;
        nextBackupAt: number | null;
        oneFileSystem: boolean;
        repository: {
            compressionMode: 'auto' | 'max' | 'off' | null;
            config: {
                accessKeyId: string;
                backend: 'r2';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accessKeyId: string;
                backend: 's3';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accountKey: string;
                accountName: string;
                backend: 'azure';
                container: string;
                customPassword?: string;
                endpointSuffix?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'gcs';
                bucket: string;
                credentialsJson: string;
                projectId: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'local';
                name: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                path?: string;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'rest';
                url: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                password?: string;
                path?: string;
                username?: string;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                privateKey: string;
                user: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                customPassword?: string;
                isExistingRepository?: boolean;
                knownHosts?: string;
            };
            createdAt: number;
            id: string;
            lastChecked: number | null;
            lastError: string | null;
            name: string;
            shortId: string;
            status: 'error' | 'healthy' | 'unknown' | null;
            type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
            updatedAt: number;
        };
        repositoryId: string;
        retentionPolicy: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        } | null;
        shortId: string;
        updatedAt: number;
        volume: {
            autoRemount: boolean;
            config: {
                backend: 'directory';
                path: string;
                readOnly?: false;
            } | {
                backend: 'nfs';
                exportPath: string;
                server: string;
                version: '3' | '4' | '4.1';
                port?: number;
                readOnly?: boolean;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                readOnly?: boolean;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                username: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                knownHosts?: string;
                password?: string;
                privateKey?: string;
                readOnly?: boolean;
            } | {
                backend: 'smb';
                password: string;
                server: string;
                share: string;
                username: string;
                vers?: '1.0' | '2.0' | '2.1' | '3.0';
                port?: number;
                domain?: string;
                readOnly?: boolean;
            } | {
                backend: 'webdav';
                path: string;
                server: string;
                port?: number;
                password?: string;
                readOnly?: boolean;
                ssl?: boolean;
                username?: string;
            };
            createdAt: number;
            id: number;
            lastError: string | null;
            lastHealthCheck: number;
            name: string;
            shortId: string;
            status: 'error' | 'mounted' | 'unmounted';
            type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
            updatedAt: number;
        };
        volumeId: number;
    };
};

export type GetBackupScheduleResponse = GetBackupScheduleResponses[keyof GetBackupScheduleResponses];

export type UpdateBackupScheduleData = {
    body?: {
        cronExpression: string;
        repositoryId: string;
        enabled?: boolean;
        excludeIfPresent?: Array<string>;
        excludePatterns?: Array<string>;
        includePatterns?: Array<string>;
        name?: string;
        oneFileSystem?: boolean;
        retentionPolicy?: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        };
        tags?: Array<string>;
    };
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}';
};

export type UpdateBackupScheduleResponses = {
    /**
     * Backup schedule updated successfully
     */
    200: {
        createdAt: number;
        cronExpression: string;
        enabled: boolean;
        excludeIfPresent: Array<string> | null;
        excludePatterns: Array<string> | null;
        id: number;
        includePatterns: Array<string> | null;
        lastBackupAt: number | null;
        lastBackupError: string | null;
        lastBackupStatus: 'error' | 'in_progress' | 'success' | 'warning' | null;
        name: string;
        nextBackupAt: number | null;
        oneFileSystem: boolean;
        repositoryId: string;
        retentionPolicy: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        } | null;
        shortId: string;
        updatedAt: number;
        volumeId: number;
    };
};

export type UpdateBackupScheduleResponse = UpdateBackupScheduleResponses[keyof UpdateBackupScheduleResponses];

export type GetBackupScheduleForVolumeData = {
    body?: never;
    path: {
        volumeId: string;
    };
    query?: never;
    url: '/api/v1/backups/volume/{volumeId}';
};

export type GetBackupScheduleForVolumeResponses = {
    /**
     * Backup schedule details for the volume
     */
    200: {
        createdAt: number;
        cronExpression: string;
        enabled: boolean;
        excludeIfPresent: Array<string> | null;
        excludePatterns: Array<string> | null;
        id: number;
        includePatterns: Array<string> | null;
        lastBackupAt: number | null;
        lastBackupError: string | null;
        lastBackupStatus: 'error' | 'in_progress' | 'success' | 'warning' | null;
        name: string;
        nextBackupAt: number | null;
        oneFileSystem: boolean;
        repository: {
            compressionMode: 'auto' | 'max' | 'off' | null;
            config: {
                accessKeyId: string;
                backend: 'r2';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accessKeyId: string;
                backend: 's3';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accountKey: string;
                accountName: string;
                backend: 'azure';
                container: string;
                customPassword?: string;
                endpointSuffix?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'gcs';
                bucket: string;
                credentialsJson: string;
                projectId: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'local';
                name: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                path?: string;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'rest';
                url: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                password?: string;
                path?: string;
                username?: string;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                privateKey: string;
                user: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                customPassword?: string;
                isExistingRepository?: boolean;
                knownHosts?: string;
            };
            createdAt: number;
            id: string;
            lastChecked: number | null;
            lastError: string | null;
            name: string;
            shortId: string;
            status: 'error' | 'healthy' | 'unknown' | null;
            type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
            updatedAt: number;
        };
        repositoryId: string;
        retentionPolicy: {
            keepDaily?: number;
            keepHourly?: number;
            keepLast?: number;
            keepMonthly?: number;
            keepWeekly?: number;
            keepWithinDuration?: string;
            keepYearly?: number;
        } | null;
        shortId: string;
        updatedAt: number;
        volume: {
            autoRemount: boolean;
            config: {
                backend: 'directory';
                path: string;
                readOnly?: false;
            } | {
                backend: 'nfs';
                exportPath: string;
                server: string;
                version: '3' | '4' | '4.1';
                port?: number;
                readOnly?: boolean;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                readOnly?: boolean;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                username: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                knownHosts?: string;
                password?: string;
                privateKey?: string;
                readOnly?: boolean;
            } | {
                backend: 'smb';
                password: string;
                server: string;
                share: string;
                username: string;
                vers?: '1.0' | '2.0' | '2.1' | '3.0';
                port?: number;
                domain?: string;
                readOnly?: boolean;
            } | {
                backend: 'webdav';
                path: string;
                server: string;
                port?: number;
                password?: string;
                readOnly?: boolean;
                ssl?: boolean;
                username?: string;
            };
            createdAt: number;
            id: number;
            lastError: string | null;
            lastHealthCheck: number;
            name: string;
            shortId: string;
            status: 'error' | 'mounted' | 'unmounted';
            type: 'directory' | 'nfs' | 'rclone' | 'sftp' | 'smb' | 'webdav';
            updatedAt: number;
        };
        volumeId: number;
    } | null;
};

export type GetBackupScheduleForVolumeResponse = GetBackupScheduleForVolumeResponses[keyof GetBackupScheduleForVolumeResponses];

export type RunBackupNowData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/run';
};

export type RunBackupNowResponses = {
    /**
     * Backup started successfully
     */
    200: {
        success: boolean;
    };
};

export type RunBackupNowResponse = RunBackupNowResponses[keyof RunBackupNowResponses];

export type StopBackupData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/stop';
};

export type StopBackupErrors = {
    /**
     * No backup is currently running for this schedule
     */
    409: unknown;
};

export type StopBackupResponses = {
    /**
     * Backup stopped successfully
     */
    200: {
        success: boolean;
    };
};

export type StopBackupResponse = StopBackupResponses[keyof StopBackupResponses];

export type RunForgetData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/forget';
};

export type RunForgetResponses = {
    /**
     * Retention policy applied successfully
     */
    200: {
        success: boolean;
    };
};

export type RunForgetResponse = RunForgetResponses[keyof RunForgetResponses];

export type GetScheduleNotificationsData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/notifications';
};

export type GetScheduleNotificationsResponses = {
    /**
     * List of notification assignments for the schedule
     */
    200: Array<{
        createdAt: number;
        destination: {
            config: {
                apiToken: string;
                priority: -1 | 0 | 1;
                type: 'pushover';
                userKey: string;
                devices?: string;
            } | {
                botToken: string;
                chatId: string;
                type: 'telegram';
            } | {
                from: string;
                smtpHost: string;
                smtpPort: number;
                to: Array<string>;
                type: 'email';
                useTLS: boolean;
                password?: string;
                username?: string;
            } | {
                priority: 'default' | 'high' | 'low' | 'max' | 'min';
                topic: string;
                type: 'ntfy';
                password?: string;
                serverUrl?: string;
                username?: string;
            } | {
                priority: number;
                serverUrl: string;
                token: string;
                type: 'gotify';
                path?: string;
            } | {
                shoutrrrUrl: string;
                type: 'custom';
            } | {
                type: 'discord';
                webhookUrl: string;
                avatarUrl?: string;
                threadId?: string;
                username?: string;
            } | {
                type: 'slack';
                webhookUrl: string;
                channel?: string;
                iconEmoji?: string;
                username?: string;
            };
            createdAt: number;
            enabled: boolean;
            id: number;
            name: string;
            type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
            updatedAt: number;
        };
        destinationId: number;
        notifyOnFailure: boolean;
        notifyOnStart: boolean;
        notifyOnSuccess: boolean;
        notifyOnWarning: boolean;
        scheduleId: number;
    }>;
};

export type GetScheduleNotificationsResponse = GetScheduleNotificationsResponses[keyof GetScheduleNotificationsResponses];

export type UpdateScheduleNotificationsData = {
    body?: {
        assignments: Array<{
            destinationId: number;
            notifyOnFailure: boolean;
            notifyOnStart: boolean;
            notifyOnSuccess: boolean;
            notifyOnWarning: boolean;
        }>;
    };
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/notifications';
};

export type UpdateScheduleNotificationsResponses = {
    /**
     * Notification assignments updated successfully
     */
    200: Array<{
        createdAt: number;
        destination: {
            config: {
                apiToken: string;
                priority: -1 | 0 | 1;
                type: 'pushover';
                userKey: string;
                devices?: string;
            } | {
                botToken: string;
                chatId: string;
                type: 'telegram';
            } | {
                from: string;
                smtpHost: string;
                smtpPort: number;
                to: Array<string>;
                type: 'email';
                useTLS: boolean;
                password?: string;
                username?: string;
            } | {
                priority: 'default' | 'high' | 'low' | 'max' | 'min';
                topic: string;
                type: 'ntfy';
                password?: string;
                serverUrl?: string;
                username?: string;
            } | {
                priority: number;
                serverUrl: string;
                token: string;
                type: 'gotify';
                path?: string;
            } | {
                shoutrrrUrl: string;
                type: 'custom';
            } | {
                type: 'discord';
                webhookUrl: string;
                avatarUrl?: string;
                threadId?: string;
                username?: string;
            } | {
                type: 'slack';
                webhookUrl: string;
                channel?: string;
                iconEmoji?: string;
                username?: string;
            };
            createdAt: number;
            enabled: boolean;
            id: number;
            name: string;
            type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
            updatedAt: number;
        };
        destinationId: number;
        notifyOnFailure: boolean;
        notifyOnStart: boolean;
        notifyOnSuccess: boolean;
        notifyOnWarning: boolean;
        scheduleId: number;
    }>;
};

export type UpdateScheduleNotificationsResponse = UpdateScheduleNotificationsResponses[keyof UpdateScheduleNotificationsResponses];

export type GetScheduleMirrorsData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/mirrors';
};

export type GetScheduleMirrorsResponses = {
    /**
     * List of mirror repository assignments for the schedule
     */
    200: Array<{
        createdAt: number;
        enabled: boolean;
        lastCopyAt: number | null;
        lastCopyError: string | null;
        lastCopyStatus: 'error' | 'success' | null;
        repository: {
            compressionMode: 'auto' | 'max' | 'off' | null;
            config: {
                accessKeyId: string;
                backend: 'r2';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accessKeyId: string;
                backend: 's3';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accountKey: string;
                accountName: string;
                backend: 'azure';
                container: string;
                customPassword?: string;
                endpointSuffix?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'gcs';
                bucket: string;
                credentialsJson: string;
                projectId: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'local';
                name: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                path?: string;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'rest';
                url: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                password?: string;
                path?: string;
                username?: string;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                privateKey: string;
                user: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                customPassword?: string;
                isExistingRepository?: boolean;
                knownHosts?: string;
            };
            createdAt: number;
            id: string;
            lastChecked: number | null;
            lastError: string | null;
            name: string;
            shortId: string;
            status: 'error' | 'healthy' | 'unknown' | null;
            type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
            updatedAt: number;
        };
        repositoryId: string;
        scheduleId: number;
    }>;
};

export type GetScheduleMirrorsResponse = GetScheduleMirrorsResponses[keyof GetScheduleMirrorsResponses];

export type UpdateScheduleMirrorsData = {
    body?: {
        mirrors: Array<{
            enabled: boolean;
            repositoryId: string;
        }>;
    };
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/mirrors';
};

export type UpdateScheduleMirrorsResponses = {
    /**
     * Mirror assignments updated successfully
     */
    200: Array<{
        createdAt: number;
        enabled: boolean;
        lastCopyAt: number | null;
        lastCopyError: string | null;
        lastCopyStatus: 'error' | 'success' | null;
        repository: {
            compressionMode: 'auto' | 'max' | 'off' | null;
            config: {
                accessKeyId: string;
                backend: 'r2';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accessKeyId: string;
                backend: 's3';
                bucket: string;
                endpoint: string;
                secretAccessKey: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                accountKey: string;
                accountName: string;
                backend: 'azure';
                container: string;
                customPassword?: string;
                endpointSuffix?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'gcs';
                bucket: string;
                credentialsJson: string;
                projectId: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'local';
                name: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                path?: string;
            } | {
                backend: 'rclone';
                path: string;
                remote: string;
                customPassword?: string;
                isExistingRepository?: boolean;
            } | {
                backend: 'rest';
                url: string;
                customPassword?: string;
                isExistingRepository?: boolean;
                password?: string;
                path?: string;
                username?: string;
            } | {
                backend: 'sftp';
                host: string;
                path: string;
                privateKey: string;
                user: string;
                port?: number;
                skipHostKeyCheck?: boolean;
                customPassword?: string;
                isExistingRepository?: boolean;
                knownHosts?: string;
            };
            createdAt: number;
            id: string;
            lastChecked: number | null;
            lastError: string | null;
            name: string;
            shortId: string;
            status: 'error' | 'healthy' | 'unknown' | null;
            type: 'azure' | 'gcs' | 'local' | 'r2' | 'rclone' | 'rest' | 's3' | 'sftp';
            updatedAt: number;
        };
        repositoryId: string;
        scheduleId: number;
    }>;
};

export type UpdateScheduleMirrorsResponse = UpdateScheduleMirrorsResponses[keyof UpdateScheduleMirrorsResponses];

export type GetMirrorCompatibilityData = {
    body?: never;
    path: {
        scheduleId: string;
    };
    query?: never;
    url: '/api/v1/backups/{scheduleId}/mirrors/compatibility';
};

export type GetMirrorCompatibilityResponses = {
    /**
     * List of repositories with their mirror compatibility status
     */
    200: Array<{
        compatible: boolean;
        reason: string | null;
        repositoryId: string;
    }>;
};

export type GetMirrorCompatibilityResponse = GetMirrorCompatibilityResponses[keyof GetMirrorCompatibilityResponses];

export type ReorderBackupSchedulesData = {
    body?: {
        scheduleIds: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/backups/reorder';
};

export type ReorderBackupSchedulesResponses = {
    /**
     * Backup schedules reordered successfully
     */
    200: {
        success: boolean;
    };
};

export type ReorderBackupSchedulesResponse = ReorderBackupSchedulesResponses[keyof ReorderBackupSchedulesResponses];

export type ListNotificationDestinationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/destinations';
};

export type ListNotificationDestinationsResponses = {
    /**
     * A list of notification destinations
     */
    200: Array<{
        config: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        createdAt: number;
        enabled: boolean;
        id: number;
        name: string;
        type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
        updatedAt: number;
    }>;
};

export type ListNotificationDestinationsResponse = ListNotificationDestinationsResponses[keyof ListNotificationDestinationsResponses];

export type CreateNotificationDestinationData = {
    body?: {
        config: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/notifications/destinations';
};

export type CreateNotificationDestinationResponses = {
    /**
     * Notification destination created successfully
     */
    201: {
        config: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        createdAt: number;
        enabled: boolean;
        id: number;
        name: string;
        type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
        updatedAt: number;
    };
};

export type CreateNotificationDestinationResponse = CreateNotificationDestinationResponses[keyof CreateNotificationDestinationResponses];

export type DeleteNotificationDestinationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/destinations/{id}';
};

export type DeleteNotificationDestinationErrors = {
    /**
     * Notification destination not found
     */
    404: unknown;
};

export type DeleteNotificationDestinationResponses = {
    /**
     * Notification destination deleted successfully
     */
    200: {
        message: string;
    };
};

export type DeleteNotificationDestinationResponse = DeleteNotificationDestinationResponses[keyof DeleteNotificationDestinationResponses];

export type GetNotificationDestinationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/destinations/{id}';
};

export type GetNotificationDestinationErrors = {
    /**
     * Notification destination not found
     */
    404: unknown;
};

export type GetNotificationDestinationResponses = {
    /**
     * Notification destination details
     */
    200: {
        config: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        createdAt: number;
        enabled: boolean;
        id: number;
        name: string;
        type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
        updatedAt: number;
    };
};

export type GetNotificationDestinationResponse = GetNotificationDestinationResponses[keyof GetNotificationDestinationResponses];

export type UpdateNotificationDestinationData = {
    body?: {
        config?: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        enabled?: boolean;
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/destinations/{id}';
};

export type UpdateNotificationDestinationErrors = {
    /**
     * Notification destination not found
     */
    404: unknown;
};

export type UpdateNotificationDestinationResponses = {
    /**
     * Notification destination updated successfully
     */
    200: {
        config: {
            apiToken: string;
            priority: -1 | 0 | 1;
            type: 'pushover';
            userKey: string;
            devices?: string;
        } | {
            botToken: string;
            chatId: string;
            type: 'telegram';
        } | {
            from: string;
            smtpHost: string;
            smtpPort: number;
            to: Array<string>;
            type: 'email';
            useTLS: boolean;
            password?: string;
            username?: string;
        } | {
            priority: 'default' | 'high' | 'low' | 'max' | 'min';
            topic: string;
            type: 'ntfy';
            password?: string;
            serverUrl?: string;
            username?: string;
        } | {
            priority: number;
            serverUrl: string;
            token: string;
            type: 'gotify';
            path?: string;
        } | {
            shoutrrrUrl: string;
            type: 'custom';
        } | {
            type: 'discord';
            webhookUrl: string;
            avatarUrl?: string;
            threadId?: string;
            username?: string;
        } | {
            type: 'slack';
            webhookUrl: string;
            channel?: string;
            iconEmoji?: string;
            username?: string;
        };
        createdAt: number;
        enabled: boolean;
        id: number;
        name: string;
        type: 'custom' | 'discord' | 'email' | 'gotify' | 'ntfy' | 'pushover' | 'slack' | 'telegram';
        updatedAt: number;
    };
};

export type UpdateNotificationDestinationResponse = UpdateNotificationDestinationResponses[keyof UpdateNotificationDestinationResponses];

export type TestNotificationDestinationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/destinations/{id}/test';
};

export type TestNotificationDestinationErrors = {
    /**
     * Notification destination not found
     */
    404: unknown;
    /**
     * Cannot test disabled destination
     */
    409: unknown;
    /**
     * Failed to send test notification
     */
    500: unknown;
};

export type TestNotificationDestinationResponses = {
    /**
     * Test notification sent successfully
     */
    200: {
        success: boolean;
    };
};

export type TestNotificationDestinationResponse = TestNotificationDestinationResponses[keyof TestNotificationDestinationResponses];

export type GetSystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/info';
};

export type GetSystemInfoResponses = {
    /**
     * System information with enabled capabilities
     */
    200: {
        capabilities: {
            rclone: boolean;
            sysAdmin: boolean;
        };
    };
};

export type GetSystemInfoResponse = GetSystemInfoResponses[keyof GetSystemInfoResponses];

export type DownloadResticPasswordData = {
    body?: {
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/system/restic-password';
};

export type DownloadResticPasswordResponses = {
    /**
     * Restic password file content
     */
    200: string;
};

export type DownloadResticPasswordResponse = DownloadResticPasswordResponses[keyof DownloadResticPasswordResponses];
